debug: false

logging:
  level:
    com.backend.mes: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/athlete
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL57Dialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
server:
  port: 9081

jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJ1c2VyIn0I2qOfhAZMGSH1pCecUH5sV2Lg2pSWNQMPzXsMcne6NJ1SlkBoirhGAmKfTYNcRyhu6nQtRzgAd6VXyttoX9A
  expiration_time: 1800000
